---
title: "Models Alternative"
author: "Rosie Wu"
date: "2025-04-01"
output: html_document
---

```{r setup, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r include=FALSE}
library(here)
library(ggplot2)
library(forecast)
library(cowplot)
library(Kendall)
library(tseries)
library(kableExtra)
library(dplyr)
library(smooth)
```


# Preparation
## Upload
```{r include=FALSE}
#upload test and training data
load_daily <- read.csv("./Data/Processed/dailyload.csv")
load_hourly <- read.csv("./Data/Processed/hourlyload.csv")

#create msts
load_daily_msts <- msts(load_daily$daily_average, 
                            seasonal.periods =c(7,365.25),
                            start=c(2005,1,1)) 

load_hourly_msts <- msts(load_hourly$load, 
                            seasonal.periods =c(24,168,8766),
                            start=c(2005,1,1,1)) %>% #is this the right hour?
                         na.interp()
```

## Deseasoned
```{r}
load_daily_mstl <- mstl(load_daily_msts)

load_hourly_mstl <- mstl(load_hourly_msts)
```


# Forecasts

## Previous: TBATS Daily

```{r}
#fit TBATS
daily_tbats_fit <- tbats(load_daily_msts)

#forecasting test data
forecast_daily_tbats <- forecast(daily_tbats_fit, 
                           h = 59)

#visualization
plot(forecast_daily_tbats)

```
```{r}
#residuals and scores for seasonal naive model
residuals_daily_tbats <- checkresiduals(forecast_daily_tbats)
score_daily_snaive <- accuracy(forecast_daily_tbats, dailyload_test[,2])
score_daily_snaive
```
## ARIMA + Fourier Tweaking
```{r}
#autofit the arima model
daily_arima_fourier <- auto.arima(load_daily_msts,
                                   xreg = fourier(load_daily_msts, 
                                                  K = c(1, 7)), 
                                   seasonal = FALSE)
print(daily_arima_fourier)

#create the arima forecast with the autofit
forecast_daily_arima_fourier <- forecast(object = daily_arima_fourier,
                                   xreg=fourier(load_daily_msts,
                                                K=c(1,7),
                                                h=59),
                                   h=59)

#plot the forecast
plot(forecast_daily_arima_fourier)

here()
#write into csv
write.csv(forecast_daily_arima_fourier, 
          file = "./Forecasts/forecast_daily_arima_fourier_rosie.csv",
          row.names = FALSE)
```
```{r}
#residuals and scores for seasonal naive model
residuals_daily_arima_fourier <- checkresiduals(forecast_daily_arima_fourier)
score_daily_arima_fourier <- accuracy(forecast_daily_arima_fourier, dailyload_test[,2])
score_daily_arima_fourier
```


```{r echo=FALSE}
#autofit the arima model
hourly_arima_autofit <- auto.arima(load_hourly_msts,
                                   xreg = fourier(load_hourly_msts, 
                                                  K = c(1, 1, 6)), 
                                   seasonal = FALSE)
print(hourly_arima_autofit)

#create the arima forecast with the autofit
forecast_hourly_arima <- forecast(object = load_hourly_msts,
                                   xreg=fourier(load_hourly_msts,
                                                K=c(1,1,6),
                                                h=59*24),
                                   h=59*24)

#plot the forecast
plot(forecast_hourly_arima)

here()
#write into csv
write.csv(forecast_hourly_arima, 
          file = "./Forecasts/forecast_hourly_arima_rosie.csv",
          row.names = FALSE)
```


# Trying to debug this model still: this should help find the best Fourier terms but I'm  still using AI to debug and revise

```{r}
# Function to find optimal K for Fourier terms in ARIMA
find_best_k <- function(ts_data, max_k = 5) {
  # Ensure we have a valid seasonal period
  freq <- frequency(ts_data)
  if(is.null(freq) || freq <= 1) {
    stop("Time series must have a seasonal period (frequency > 1)")
  }
  
  best_aic <- Inf
  best_k <- 1
  best_model <- NULL
  
  for (k in 1:max_k) {
    tryCatch({
      fourier_terms <- cbind(
        fourier(ts_data, K = c(k_weekly, k_yearly)), 
        seasons = c(7, 365.25))

      current_model <- auto.arima(ts_data,
                                xreg = fourier_terms,
                                seasonal = FALSE,
                                stepwise = TRUE,
                                approximation = FALSE)
      
      if (current_model$aic < best_aic) {
        best_aic <- current_model$aic
        best_k <- k
        best_model <- current_model
      }
    }, error = function(e) {
      message(paste("Error with K =", k, ":", e$message))
    })
  }
  
  if(is.null(best_model)) {
    stop("No valid models found with the tested K values")
  }
  
  return(list(model = best_model, best_k = best_k, best_aic = best_aic))
}
  

# Usage with your data
result <- find_best_k(load_daily_msts, max_k = 5)

# The best model
daily_arima_autofit <- result$model

# The optimal K value
optimal_k <- result$best_k

# Print results
cat("Optimal K:", optimal_k, "\n")
cat("Best AIC:", result$best_aic, "\n")
print(summary(daily_arima_autofit))
```



## Exponential Smoothing

### Daily ES

```{r}
daily_es_fit <- es(load_daily_msts,model="ZZZ",h=59,holdout=FALSE)
#forecasting test data
forecast_daily_es <- forecast(daily_es_fit, h= 58)

#visualization
plot(forecast_daily_es)
score_forecast_daily_es <- accuracy(forecast_daily_es, dailyload_test[,2])
score_forecast_daily_es

here()
#write into csv
write.csv(forecast_daily_es, 
          file = "./Forecasts/forecast_daily_es.csv",
          row.names = FALSE)
```
Extremely high MAPE and RMSE scores, so need tweaking further or change to a different model.

### Hourly ES
```{r}
hourly_es_fit <- es(load_hourly_msts,model="ZZZ", h=59*24,holdout=FALSE)
#forecasting test data
forecast_hourly_es <- forecast(hourly_es_fit, h=59*24-1)

#visualization
plot(forecast_hourly_es)
score_forecast_hourly_es <- accuracy(forecast_hourly_es, dailyload_test[,2])
score_forecast_hourly_es

here()
#write into csv
write.csv(forecast_hourly_es, 
          file = "./Forecasts/forecast_hourly_es.csv",
          row.names = FALSE)
```

## StructTS 
### daily
```{r}
daily_ss_fit <- StructTS(load_daily_msts,
                    type="BSM",fixed=c(NA,NA,NA,NA))   #this function has convergence issues
checkresiduals(daily_ss_fit)
```

```{r}
daily_ss_fit <- StructTS(load_daily_msts,
                    type="BSM",fixed=c(0.1,0.01,0.3,NA)) 

#this function has convergence issues
checkresiduals(daily_ss_fit)

#Generating forecasts
# StructTS() does not call the forecast() internally so we need one more step
forecast_daily_ss <- forecast(daily_ss_fit,h=59)
plot(forecast_daily_ss)


score_forecast_daily_es <- accuracy(forecast_daily_ss, dailyload_test[,2])
score_forecast_daily_es

here()
#write into csv
write.csv(forecast_hourly_es, 
          file = "./Forecasts/forecast_daily_ss.csv",
          row.names = FALSE)
```

