---
title: "Data Wrangling"
author: "Rachael Stephan & Rosie Wu
editor_options: 
  chunk_output_type: console
---

```{r chunks, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r libraries, include = FALSE}
#retrieve libraries
library(here); library(ggplot2); library(forecast)
library(tidyverse)
```

```{r theme, include=FALSE}
#create plot theme
mytheme <- theme_bw(base_size = 10)+
  theme(axis.title = element_text(size = 10, hjust = 0.5),
        plot.title.position = "panel",
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.25),
        plot.caption = element_text(hjust = 0),
        legend.box = "vertical",
        legend.location = "plot",
        axis.gridlines = element_line(color = "grey", linewidth = 0.25),
        axis.ticks = element_line(color = "black", linewidth = 0.5),
        axis.grid = element_blank())

#set plot theme
theme_set(mytheme)
```

# Data Upload

```{r upload}
#load data and create a daily average data frame
dailyload <- readxl::read_xlsx("./Data/Raw/load.xlsx") %>%
    mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%  
    rowwise() %>%
    mutate(daily_average = mean(c_across(h1:h24), na.rm = TRUE)) %>%  
    ungroup() %>%
    select(-c(h1:h24), -meter_id)

hourlyload <- readxl::read_xlsx("./Data/Raw/load.xlsx") %>%
    mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%  
    pivot_longer(cols = starts_with("h"),
                 names_to = "hour",
                 values_to = "load")%>%
    mutate(hour = as.integer(substring(hour,2))) %>%
    select(-meter_id)

#load exogenous variables
library(dplyr)
library(readxl)

humidity <- readxl::read_xlsx("./Data/Raw/relative_humidity.xlsx") %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%
  group_by(date) %>%
  summarise(humidity = mean(c_across(rh_ws1:rh_ws24), na.rm = TRUE))


#load exogenous variables
temperature <- readxl::read_xlsx("./Data/Raw/temperature.xlsx") %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d")) %>%
  group_by(date) %>%
  summarise(temp = mean(c_across(t_ws1:t_ws24), na.rm = TRUE))
```

## Section Data

```{r}
dailyload_train <- head(dailyload,
                        (length(dailyload$daily_average)-50))

dailyload_test <- tail(dailyload, 50)

temp_train <- head(temperature,
                        (length(dailyload$daily_average)-50))

temp_test <- tail(temperature, 50)

humidity_train <- head(humidity,
                        (length(dailyload$daily_average)-50))

humidity_test <- tail(humidity, 50)
```

# Save Processed Data

```{r}
write.csv(dailyload, file = "~/Duke_R/TSA_Forecasting/Data/Processed/dailyload.csv",
          row.names = FALSE)

write.csv(dailyload_train, file = "~/Duke_R/TSA_Forecasting/Data/Processed/dailyload_train.csv",
          row.names = FALSE)

write.csv(dailyload_test, file = "~/Duke_R/TSA_Forecasting/Data/Processed/dailyload_test.csv",
          row.names = FALSE)

write.csv(temp_test, file = "~/Duke_R/TSA_Forecasting/Data/Processed/temp_test.csv",
          row.names = FALSE)

write.csv(temp_train, file = "~/Duke_R/TSA_Forecasting/Data/Processed/temp_train.csv",
          row.names = FALSE)

write.csv(temperature, file = "~/Duke_R/TSA_Forecasting/Data/Processed/temp_all.csv",
          row.names = FALSE)

write.csv(humidity_test, file = "~/Duke_R/TSA_Forecasting/Data/Processed/humidity_test.csv",
          row.names = FALSE)

write.csv(humidity_train, file = "~/Duke_R/TSA_Forecasting/Data/Processed/humidity_train.csv",
          row.names = FALSE)

write.csv(humidity, file = "~/Duke_R/TSA_Forecasting/Data/Processed/humidity_all.csv",
          row.names = FALSE)

write.csv(hourlyload, file = "~/Duke_R/TSA_Forecasting/Data/Processed/hourlyload.csv",
          row.names = FALSE)
```

# Basic Visualization

```{r}
daily_ts <- ts(dailyload[,2],
               start = c(2005,01,01),
               frequency = 365)

autoplot(daily_ts)
```

